version: '3.4'


services:
  app:
    image: jsanweb/dswarm-app
    build: ./app
    container_name: app
    networks:
      - backend
    ports:
      - '8000'
    volumes:
      - ./app:/usr/src/app
    command: gunicorn app.main:application -c app/gunicornconfig.py
    deploy:
      replicas: 8

  nginx:
    image: jsanweb/dswarm-nginx
    build: ./nginx
    container_name: nginx
    networks:
      - backend
    depends_on:
      - app
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf


networks:
  backend:
